### ISSUE TITLE
Is .NET Core supported?

### ISSUE THREAD

**Issue by vadi2** [Flose/UpdateLib#1]
I have a cross-platform (windows, macos, linux) .NET Core application built with Qml.Net for the interface. Can I use UpdateLib to provide updates, or it it tied to Windows-only Forms for the UI?

**Comment by AsamK** [comment]
Yeah, it's pretty much tied to Windows.Forms for the UI, so it won't work with .NET Core on macos/linux.
It runs fine with the Mono implementation of Windows.Forms, however it's a pain to setup on macOS, because that needs an X server.

**Comment by vadi2** [comment]
Alright, thanks.
